"""employee table modified + modif task

Revision ID: 03183ff7df57
Revises: a0eec23297ca
Create Date: 2026-08-11 09:18:20.338154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03183ff7df57'
down_revision: Union[str, Sequence[str], None] = 'a0eec23297ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employe', 'salary',
               existing_type=sa.NUMERIC(precision=7, scale=2),
               type_=sa.Numeric(precision=8, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employe', 'salary',
               existing_type=sa.Numeric(precision=8, scale=2),
               type_=sa.NUMERIC(precision=7, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###
