"""employee table added

Revision ID: a0eec23297ca
Revises: 4598bbce3cf0
Create Date: 2026-08-10 18:16:26.893245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0eec23297ca'
down_revision: Union[str, Sequence[str], None] = '4598bbce3cf0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employe',
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('salary', sa.NUMERIC(precision=7, scale=2), nullable=False),
    sa.Column('titre', sa.Enum('PM', 'DEV', name='titre'), nullable=False),
    sa.Column('supervisor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['supervisor_id'], ['employe.employee_id'], ),
    sa.PrimaryKeyConstraint('employee_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employe')
    # ### end Alembic commands ###
