"""tables modified

Revision ID: d053d5875c7d
Revises: 5d358eae3820
Create Date: 2026-08-11 15:43:54.801323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd053d5875c7d'
down_revision: Union[str, Sequence[str], None] = '5d358eae3820'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'employe', ['email'])
    op.alter_column('tasks', 'assign_to_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'assign_to_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'employe', type_='unique')
    # ### end Alembic commands ###
